---
- name: Add Docker repository key
  become: true
  ansible.builtin.copy:
    src: "files/docker.gpg"
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "644"

- name: Add docker APT repo
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    mode: "0644"
    state: present

- name: Add docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add docker_users to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
    cache_valid_time: 1800
