---
- name: Add Docker repository key
  become: true
  ansible.builtin.copy:
    src: "files/docker.gpg"
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: "644"

- name: Remove old docker repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://apt.dockerproject.org/repo debian-{{ ansible_distribution_release }} main"
    mode: "0644"
    state: absent

- name: Remove old docker repository key
  become: true
  ansible.builtin.apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: absent

- name: Add docker APT repo
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    mode: "0644"
    state: present

- name: Add docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
    cache_valid_time: 1800

- name: Install docker-compose
  when: docker_install_compose | bool
  ansible.builtin.apt:
    name:
      - docker-compose
    state: present
    update_cache: true
    cache_valid_time: 1800
